name: teeth
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - astor=0.8.1
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - blosc=1.20.0
  - brotli=1.0.9
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.6.20
  - cairo=1.16.0
  - certifi=2020.6.20
  - cffi=1.14.0
  - charls=2.1.0
  - cloudpickle=1.6.0
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - cupti=10.0.130
  - cycler=0.10.0
  - cython=0.29.21
  - cytoolz=0.10.1
  - dask-core=2.25.0
  - dbus=1.13.6
  - decorator=4.4.2
  - easydict=1.9
  - expat=2.2.9
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.2
  - gast=0.2.2
  - geos=3.8.1
  - gettext=0.19.8.1
  - giflib=5.2.1
  - glib=2.65.0
  - gmp=6.2.0
  - gnutls=3.6.13
  - google-pasta=0.2.0
  - graphite2=1.3.13
  - grpcio=1.31.0
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - h5py=2.10.0
  - harfbuzz=2.4.0
  - hdf5=1.10.6
  - icu=64.2
  - imagecodecs=2020.5.30
  - imageio=2.9.0
  - importlib-metadata=1.7.0
  - intel-openmp=2020.1
  - ipdb=0.13.3
  - ipython=7.18.1
  - ipython_genutils=0.2.0
  - jasper=1.900.1
  - jedi=0.15.2
  - joblib=0.16.0
  - jpeg=9d
  - json_tricks=3.15.2
  - jxrlib=1.1
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libllvm9=9.0.1
  - libopencv=4.4.0
  - libpng=1.6.37
  - libprotobuf=3.13.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.10
  - libxslt=1.1.33
  - libzopfli=1.0.3
  - lxml=4.5.2
  - lz4-c=1.9.2
  - markdown=3.2.2
  - matplotlib-base=3.3.1
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - nettle=3.4.1
  - networkx=2.5
  - ninja=1.10.1
  - nspr=4.27
  - nss=3.55
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - opencv=4.4.0
  - openh264=2.1.1
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - opt_einsum=3.1.0
  - pandas=1.1.0
  - parso=0.5.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.2.2
  - pixman=0.38.0
  - prompt-toolkit=3.0.7
  - protobuf=3.13.0
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py-opencv=4.4.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyparsing=2.4.7
  - python=3.7.8
  - python-dateutil=2.8.1
  - python-docx=0.8.10
  - python_abi=3.7
  - pytorch=1.1.0
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - qt=5.12.5
  - readline=8.0
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - setuptools=49.6.0
  - shapely=1.7.1
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.33.0
  - tensorboard=1.15.0
  - tensorboardx=2.1
  - tensorflow=1.15.0
  - tensorflow-base=1.15.0
  - tensorflow-estimator=1.15.1
  - tensorflow-gpu=1.15.0
  - termcolor=1.1.0
  - threadpoolctl=2.1.0
  - tifffile=2020.9.3
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - tqdm=4.48.2
  - traitlets=5.0.4
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=0.16.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.11
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yacs=0.1.6
  - yaml=0.2.5
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
