name: hrnet
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - argon2-cffi=20.1.0
  - attrs=20.1.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - bleach=3.1.5
  - brotlipy=0.7.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - cffi=1.14.1
  - chardet=3.0.4
  - cryptography=3.0
  - cuda92=1.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - intel-openmp=2020.1
  - ipdb=0.13.3
  - ipykernel=5.3.4
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jinja2=2.11.2
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.6.3
  - jupyterlab=2.2.6
  - jupyterlab_server=1.2.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - notebook=6.1.3
  - numpy=1.19.1
  - numpy-base=1.19.1
  - openssl=1.1.1g
  - packaging=20.4
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.2.2
  - prometheus_client=0.8.0
  - prompt_toolkit=1.0.15
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytorch=0.4.1
  - pyzmq=19.0.2
  - readline=8.0
  - requests=2.24.0
  - send2trash=1.5.0
  - setuptools=49.6.0
  - simplegeneric=0.8.1
  - six=1.15.0
  - sqlite=3.33.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - cycler==0.10.0
    - cython==0.29.21
    - detail==4.0
    - easydict==1.7
    - imageio==2.9.0
    - json-tricks==3.15.2
    - kiwisolver==1.2.0
    - matplotlib==3.3.1
    - networkx==2.5
    - ninja==1.10.0.post1
    - opencv-python==3.4.1.15
    - pandas==1.1.1
    - pillow==7.2.0
    - protobuf==3.13.0
    - pytz==2020.1
    - pywavelets==1.1.1
    - pyyaml==5.3.1
    - scikit-image==0.17.2
    - scipy==1.5.2
    - shapely==1.6.4
    - tensorboardx==2.1
    - tifffile==2020.8.13
    - tqdm==4.48.2
    - yacs==0.1.8
